'https://gemini.google.com/app/87111578dee1961a'

'https://gemini.google.com/app/dbe633a02315825c?hl=vi%20H%E1%BB%99p%20th%C6%B0%20%C4%91%E1%BA%BFn'

'https://gemini.google.com/app/dbe633a02315825c?hl=vi%20H%E1%BB%99p%20th%C6%B0%20%C4%91%E1%BA%BFn'


'''
mày phải tượng tượng khi diễn nó cũng sẽ đi từ đăng nhập hệ thống--> trang home--> modules -->giả sử click vào module hệ thống--> sidebar (thanh cuộn hay không)--> menu cha-->menu con --> giao diện menu con có gì (bảng , các nút trong giao diện cả trên và dưới bảng, có cột chức năng các nút ẩn, trường dữ liệu, thanh cuộn,....) nói chung là phải lấy hết mới được thì video mới thành công diễn như người thật
mày phải ra kịch bản các bước trình tự chứ tao thấy như vậy chưa ổn: ví dụ để hướng dẫn nhạp mới chi nhánh thì sau đăng nhập nó biết nó đang ở trang nào (cụ thể là trang Home), sau đó nó hướng dẫn đi trình tự như click vào module hệ thống, tại menu siderbar, click vào thông tin công ty, tìm đến thẻ chi nhánh, lúc này form chi nhánh hiện lên thì click vào nút tạo mới, tại đây form tạo mới hiện ra mới nhập các trường dữ liệu ở đây, làm như vậy con Bot nó không bị ngáo


'''

'''
GIAI ĐOẠN 1: QUÉT HIỆN TRƯỜNG TỔNG THỂ (GLOBAL CONTEXT)Trước khi bấm nút, Bot phải biết nó đang ở đâu để AI viết lời dẫn nhập.Dữ liệu lấy:Định danh: URL, Breadcrumbs (ví dụ: Danh mục > Hàng hóa), Tiêu đề trang.Menu (Sidebar): Quét toàn bộ danh sách label, xem cái nào đang mở (expanded), cái nào đang chọn (selected).Thanh cuộn Menu: Lấy trạng thái cuộn dọc/ngang của Sidebar để biết mục "Báo cáo" có đang bị khuất không.Mục đích: AI sẽ nói: "Chào các ông, hôm nay tôi hướng dẫn phần Quản lý kho, các ông nhìn menu bên trái nhé..."GIAI ĐOẠN 2: QUÉT MA TRẬN DỮ LIỆU (GRID SCAN)Đây là phần lấy "xương sườn" của bảng tính.Dữ liệu lấy:Cột (Headers): Lấy 100% tên các cột (Mã hàng, Tiền công, Phổ tuổi...).Dòng mẫu (Sample Row): Chỉ lấy 1 dòng đầu tiên để lấy Selector của các nút Sửa/Xóa/In nằm trên dòng đó.Tọa độ vùng (Table Rect): Lấy x, y, w, h của nguyên cái bảng.Thanh cuộn bảng (X/Y): Đây là then chốt. Lấy scrollWidth để biết có bao nhiêu cột đang nằm ngoài màn hình về bên phải.Mục đích: Để AI biết: "Ở bảng này có cột Tiền công, nếu không thấy thì các ông kéo ngang qua nhé".GIAI ĐOẠN 3: ĐỘT NHẬP & NỘI SOI FORM (FORM INFILTRATION)Bot tự tìm và Click nút "Thêm mới" hoặc "Tạo phiếu" để mở Dialog.Dữ liệu lấy:Ô nhập liệu (Inputs): Label, Placeholder, Kiểu dữ liệu (Ngày tháng, Số, Chữ), và quan trọng nhất là thuộc tính Required (bắt buộc).Tọa độ thực (Live Rect): Vị trí các ô nhập liệu ngay lúc đó.Cú hích (Triggering Popovers): Bot tự click vào các ô Combobox (chọn Khách, chọn Vàng). Nếu hiện ra bảng chọn phụ -> Vét sạch Header của bảng chọn đó.Mục đích: AI diễn kịch: "Khi nhấn vào ô Loại vàng, nó hiện ra bảng này, các ông chọn đúng tuổi vàng 610 nhé".GIAI ĐOẠN 4: THIẾT LẬP MẮT THẦN (ERROR SENSORS)Quét các dấu hiệu báo lỗi để xử lý tình huống "tai nạn" dữ liệu.Dữ liệu lấy:Field Error Selector: Các class báo đỏ của MUI như .Mui-error.Global Alert: Selector của các bảng báo lỗi (Alert, Snackbar, Toast).Keywords: Quét các từ khóa lỗi thường gặp như "trùng", "không khớp", "bắt buộc".Mục đích: Nếu lúc quay phim bị trùng mã vàng, AI sẽ "nhảy số": "Ấy, mã này trùng rồi, nhìn thông báo đỏ kìa, sửa lại đi ông giáo".KẾT QUẢ JSON SẼ TRẢ VỀ THEO CẤU TRÚC "SCENES" (PHÂN CẢNH)Cục JSON này sẽ chia làm các bước (Step) để Python chạy vòng lặp:Bước (Step)Hành động (Action)Dữ liệu kèm theoStep 1Di chuyểnSelector Menu, Tọa độ, Lời thoại dẫn nhập.Step 2Kích hoạtSelector nút Thêm, Tọa độ nút, Trạng thái chờ Dialog.Step 3Điền FormDanh sách ô nhập, Tọa độ từng ô, Cảm biến lỗi tại mỗi ô.Step 4Nội soiSelector Combobox, Header của bảng chọn phụ vừa hiện.Step 5Kết thúcSelector nút Lưu, Tọa độ, Kiểm tra bảng thông báo thành công/thất bại.💡 CHỐT LẠI CHO VŨ:Luồng này giúp ông có một "Bản đồ sống".Cột là để AI biết đường mà nói.Tọa độ là để Python biết đường mà vẽ khung đỏ/highlight.Thanh cuộn là để Bot không bị "chỉ vào không trung".Cảm biến lỗi là để kịch bản không bị "gãy" khi dữ liệu thực tế có vấn đề.
'''